name: Deploy to Server

on:
  push:
    branches:
      - main  # adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: action/ssh-agent@v0.5.3
      with: 
        SSH_PRIVATE_KEY: ${{ secrets.SECRETDAMITHA }}

    - name: Deploy website via SSH
      run: |
        scp -r . root@47.128.180.235:/www/wwwroot/damitha.work.gd


