name: Deploy to Server

on:
  push:
    branches:
      - main  # adjust this to your main branch namee

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key and configure known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SECRETDAMITHA }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 47.128.180.235 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy over SSH
      run: |
        ssh ubuntu@47.128.180.235 "mkdir -p /www/wwwroot/damitha.work.gd"
        scp -r . ubuntu@47.128.180.235:/www/wwwroot/damitha.work.gd
